### ISSUE TITLE
EMBL Heidelberg - 2022

### ISSUE THREAD

**Issue by unode** [carpentries-lab/deep-learning-intro#284]
This lesson was taught twice:
* on [2022-02-28 - 2022-03-02, 14:00 - 17:00 CET](https://bio-it.embl.de/events/introduction-to-deep-learning-2/).
* on [2022-11-16 - 2022-11-18, 14:00 - 17:00 CET](https://bio-it.embl.de/events/introduction-to-deep-learning-3/)

----

* How much time did you need for the material? (preferably per episode)
Not measured per episode but a total of 9 hours (including break time) was sufficient to cover all the material

* How much time did you need for the exercises?
Not individually measured.

* Where there any technical issues that arose during setup?
For some users with MacOS and M1 CPUs, installing tensorflow posed challenges.
A virtual machine in a local cloud was used as workaround.

* Where there any bugs or parts of the lesson code that did not work as expected?
No but some additional feedback may follow from our team of instructors. Suggestions of making available an instructor slide-deck or presentation were made. 
  * Instructors were aware that the materials were designed for self learning but the introduction was considered quite verbose and challenging to teach.

* Where there any incorrect or missing exercise solutions?
No

* Which parts of the lesson were confusing for learners?

* Which questions did learners ask?

**(will edit with additional info later)**

**Comment by svenvanderburg** [comment]
Thanks a lot for opening this @unode (pray).
We very recently improved macos with apple chips instructions here: #138 
And see #121 for a discussion on introductory slidedeck. I think including #164 in the introduction is a gamechanger, makes the introduction more interactive and easier to teach (you can check whether the information has landed).
